version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: cinedb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cine-network
    command: --default-authentication-plugin=mysql_native_password
      
  ecommerce-backend:
    build: ./ecommerce-backend
    container_name: ecommerce-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cinedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql-db
    networks:
      - cine-network
    restart: always
  
  ecommerce-frontend:
    build: ./ecommerce-frontend
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - ecommerce-backend
    networks:
      - cine-network

volumes:
  mysql_data:
networks:
  cine-network:
